/*!
Example schema generated by the [`schema!`](macro.schema.html) macro

The source body of this module is:
```rust
use rql::prelude::*;

/// An example user struct
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    pub name: String,
    pub email: String,
    pub admin: bool,
}

/// An example group struct
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Group {
    pub name: String,
}

/// An example group-member struct
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GroupMember {
    pub user_id: Id<User>,
    pub group_id: Id<Group>,
}

schema! {
    /// The generated schema struct
    pub ExampleSchema {
        user: User,
        group: Group,
        member: GroupMember
    }
}
```
*/

mod rql {
    pub use crate::*;
}

use rql::prelude::*;

/// An example user struct
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct User {
    pub name: String,
    pub email: String,
    pub admin: bool,
}

/// An example group struct
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct Group {
    pub name: String,
}

/// An example group-member struct
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(missing_docs)]
pub struct GroupMember {
    pub user_id: Id<User>,
    pub group_id: Id<Group>,
}

schema! {
    /// The generated schema struct
    pub ExampleSchema {
        user: User,
        group: Group,
        member: GroupMember
    }
}
